
- name: include interfaces declared in vars/ directory
  include_vars:
    file: "{{ item.path }}"
    name: "interface_{{ (item.path | splitext)[0] | replace('.','_') }}"
  with_filetree: vars/
  tags: always

- name: format interfaces list variables
  set_fact:
    interfaces: "{{ interfaces | default({}) | combine({item: lookup('vars', item)}) }}"
  loop: "{{ hostvars[inventory_hostname].keys() | select('match', '^.*interface_.*$') | list }}"
  tags: always

# - name: set-up dnsmasq
#   include: dnsmasq.yml
#
# - name: set-up network interfaces configuration
#   include: network.yml

- name: template out proxy configuration for dnsmasq
  become: yes
  template:
    src: dnsmasq/proxy.conf.j2
    dest: /etc/dnsmasq.d/_proxy.conf
    owner: root
    group: root
  notify:
  - restart dnsmasq proxy

- name: template out interfaces configuration for dnsmasq
  become: yes
  loop: "{{ interfaces | dict2items }}"
  template:
    src: dnsmasq/interface.conf.j2
    dest: /etc/dnsmasq.d/{{ item.value.name }}.conf
    owner: root
    group: root
  register: dnsmasq_instances
  notify:
  - restart dnsmasq instances

- meta: flush_handlers

- name: ensure resolv.conf is correctly configured (to 127.0.0.1)
  become: yes
  copy:
    src: files/resolv.conf
    dest: /etc/resolv.conf
    owner: root
    group: root
  tags: [interface]

- name: configure physical interfaces
  become: yes
  template:
    src: interfaces/physical.j2
    dest: /etc/network/interfaces
    owner: root
    group: root
  notify:
  - restart networking
  tags: [interface]

- name: template out bridged interface configuration for networking
  become: yes
  loop: "{{ interfaces | dict2items }}"
  template:
    src: interfaces/bridged.j2
    dest: /etc/network/interfaces.d/{{ item.value.name }}
    owner: root
    group: root
  notify:
  - restart networking
  tags: [interface]
